spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/unikoom_test
    username: imitator
    password: imitator
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
